# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1217, 832)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(20, 90, 301, 231))
        self.groupBox.setObjectName("groupBox")
        self.list_view_sub = QtWidgets.QListView(self.groupBox)
        self.list_view_sub.setGeometry(QtCore.QRect(20, 60, 256, 131))
        self.list_view_sub.setObjectName("list_view_sub")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(360, 100, 301, 231))
        self.groupBox_2.setObjectName("groupBox_2")
        self.list_view_flair = QtWidgets.QListView(self.groupBox_2)
        self.list_view_flair.setGeometry(QtCore.QRect(20, 60, 256, 131))
        self.list_view_flair.setObjectName("list_view_flair")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setGeometry(QtCore.QRect(700, 100, 301, 231))
        self.groupBox_7.setObjectName("groupBox_7")
        self.list_view_post = QtWidgets.QListView(self.groupBox_7)
        self.list_view_post.setGeometry(QtCore.QRect(20, 60, 256, 131))
        self.list_view_post.setObjectName("list_view_post")
        self.text_content = QtWidgets.QTextEdit(self.tab)
        self.text_content.setGeometry(QtCore.QRect(20, 370, 651, 391))
        self.text_content.setObjectName("text_content")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 330, 63, 20))
        self.label.setObjectName("label")
        self.text_analysis = QtWidgets.QTextEdit(self.tab)
        self.text_analysis.setGeometry(QtCore.QRect(700, 370, 451, 391))
        self.text_analysis.setObjectName("text_analysis")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(700, 340, 63, 20))
        self.label_2.setObjectName("label_2")
        self.load_data_button = QtWidgets.QPushButton(self.tab)
        self.load_data_button.setGeometry(QtCore.QRect(20, 10, 161, 61))
        self.load_data_button.setObjectName("load_data_button")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.plot_widget_1 = QtWidgets.QWidget(self.tab_2)
        self.plot_widget_1.setGeometry(QtCore.QRect(40, 20, 521, 371))
        self.plot_widget_1.setObjectName("plot_widget_1")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Проектний практикум"))
        self.groupBox.setTitle(_translate("MainWindow", "Тематика"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Розділ"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Допис"))
        self.label.setText(_translate("MainWindow", "Текст:"))
        self.label_2.setText(_translate("MainWindow", "Аналіз:"))
        self.load_data_button.setText(_translate("MainWindow", "Завантажити дані"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Меню"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Статистики"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
